[project]
name = "SDESolver"
version = "0.1.0"
description = "A simple python SDE solver library"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.0",
    "pytest>=8.3.4",
    "ruff>=0.8.2",
    "sphinx>=8.1.3",
]
